### ISSUE TITLE
Stuck on this: OSError: [Errno 8] Exec format error: '/tmp/ngrok/ngrok'

### ISSUE THREAD

**Issue by snarflakes** [gstaff/flask-ngrok#29]
Any idea why I'm getting this error with a basic test script?
i'm running the script as:
sudo python3 flaskngrokdemo.py

raspberry pi zero (not 64bit, maybe the problem?)

Name: flask-ngrok
Version: 0.0.26
Summary: A simple way to demo Flask apps from your machine.
Home-page: https://github.com/gstaff/flask-ngrok
Author: Grant Stafford
Author-email: None
License: UNKNOWN
Location: /home/pi/.local/lib/python3.7/site-packages
Requires: Flask, requests
Required-by:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/flask_ngrok.py", line 70, in start_ngrok
    ngrok_address = _run_ngrok()
  File "/usr/local/lib/python3.7/dist-packages/flask_ngrok.py", line 31, in _run_ngrok
    ngrok = subprocess.Popen([executable, 'http', '5000'])
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/tmp/ngrok/ngrok'

**Comment by srividya-p** [comment]
Any updates on this? Getting the same error on my Raspberry Pi 3B+, I have installed flask-ngrok===0.0.26 on a virtual environment and I am running the script without sudo.

[EDIT] Figured it out. Check #30
